# -*- mode: makefile-gmake -*-

MCXX := ../mmake/mcxx/cxx

all:

.PHONY: all msc17

msc17: 20170220.msc17bug.is_function.exe

20170220.msc17bug.is_function.exe: 20170220.msc17bug.is_function.cpp
	CXXKEY=v17 $(MCXX) -o $@ $<
